### ISSUE TITLE
Fancy "attempt to perform arithmetic on field 'cursor_row_prev' (a nil value)" during mid-animation floating window switching

### ISSUE THREAD

**Issue by Kypert** [gen740/SmoothCursor.nvim#10]
If the user is quick, opening a floating window mid-animation seems to trigger this issue:

```
Error executing vim.schedule lua callback: .../plugged/smoothcursor.nvim/lua/smoothcursor/callback.lua:77: attempt to perform arithmetic on field 'cursor_row_prev' (a nil value) 
stack traceback: 
        .../plugged/smoothcursor.nvim/lua/smoothcursor/callback.lua:77: in function ''                                       
        vim/_editor.lua: in function <vim/_editor.lua:0>                                                                     
Press ENTER or type command to continue                                                                                                                       
```

Please consider this scenario:

1. Open a file with reasonable number of lines.
2. `gg` - Go to top of file
3. `G` - Go to bottom of the file
4. Observe and admire "fancy" at work
5. But before the animation is completed, perform an action that opens a floating window (e.g `<leader>ss`) that takes focus
6. Now neovim throws above mentioned error and is stuck in an (infinite?) loop

`<leader>ss` could look like this: 
```
:nmap <leader>ss :lua local buf=vim.api.nvim_create_buf(false, true); vim.api.nvim_open_win(buf, true, {relative='win', row=30, col=30, width=100, height=50})<CR>
```
But a real use-case is to use `:Buffers` or `:Files` from [fzf-vim](https://github.com/junegunn/fzf.vim#commands), in an attempt to open/switch to another buffer/file.

**Comment by gen740** [comment]
Thank you for your issue!!

This bug was fixed.
