### ISSUE TITLE
[Feature Request] Could we have a toggle for `fancy.enable`?

### ISSUE THREAD

**Issue by nyngwang** [gen740/SmoothCursor.nvim#18]
Please 🥹!

**Comment by gen740** [comment]
Thank you for your feature request!
I love this idea! I will support this feature soon!!

**Comment by nyngwang** [comment]
Thank you for this beautiful plugin! "This must be a plugin done by a physicist" at first look. I always have it on now :)!

**Comment by gen740** [comment]
Done!

**Comment by gen740** [comment]
You can now toggle a fancy mode using `:SmoothCursorFancyToggle`!

**Comment by nyngwang** [comment]
@gen740 It seems that the toggle would not remove the (beautiful) tail of the cursor in my testing. Is this expected? And sorry for my late report...

**Comment by gen740** [comment]
Oops, it seems a bug.

Sorry for my late reply.

**Comment by gen740** [comment]
I fixed the bug. If you have a problem, please feel free to reopen the issue!
