### ISSUE TITLE
Error running config for SmoothCursor.nvim: .../lua/smoothcursor/init.lua:41

### ISSUE THREAD

**Issue by AllenDang** [gen740/SmoothCursor.nvim#2]
Failed to install, error message is `Error running config for SmoothCursor.nvim: .../lua/smoothcursor/init.lua:41: attampt to index field 'cmd' (a function value)`.

My env is:
neovim 0.7.2
macOS

**Comment by gen740** [comment]
Thank you for reporting.
Can you tell me your configuration?

**Comment by gen740** [comment]
Has fixed.
