### ISSUE TITLE
It would be a good default to disable this plugin on terminal buffers

### ISSUE THREAD

**Issue by nyngwang** [gen740/SmoothCursor.nvim#28]
It would be great if we could toggle off SmoothCursor for all terminal buffers, i.e. buffer of `buftype=terminal`, temporarily on `TermEnter` and re-enable it on `TermLeave`. Currently, this can be achieved by using two `autocmd`s as code provided below, but there is no way to do so using by config passing to `setup(...)`. Maybe we can add these two `autocmd`s by default since I believe we rarely need to use SmoothCurosr on terminal buffers. Or maybe you have a better idea. What do you think?

```lua
-- enable/disable for terminal buffer.
vim.api.nvim_create_autocmd({ 'TermEnter' }, {
  pattern = '*',
  callback = function () vim.cmd('SmoothCursorStop') end
})
vim.api.nvim_create_autocmd({ 'TermLeave' }, {
  pattern = '*',
  callback = function () vim.cmd('SmoothCursorStart') end
})
```

**Comment by gen740** [comment]
That's a nice idea, there is a similar option `disable_float_win`, so I will add `disable_terminal`.

**Comment by nyngwang** [comment]
> [...] , so I will add `disable_terminal`.

Maybe we don't need the option at all, since the smooth cursor will always stuck at the first line. This is the current result if I remove the two `autocmd`s in my OP:

<img src="https://user-images.githubusercontent.com/24765272/213949238-590e07fc-ddd1-469f-9f17-6d4d004fe8d6.png" width="500">

btw, happy new year!

**Comment by gen740** [comment]
Hmmm, it's better to disable it by default...

**Comment by gen740** [comment]
Merged #30.

**Comment by nyngwang** [comment]
Thanks for your fixes, but I just realized the problem still exists. The following is the config I used for testing:

```lua
use {
  'gen740/SmoothCursor.nvim',
  config = function()
    require('smoothcursor').setup {
      fancy = {
        enable = true,
      },
      threshold = 1,
      flyin_effect = 'top',
    }
  end
}
```

**Comment by gen740** [comment]
Ooops...

**Comment by nyngwang** [comment]
@gen740 (Sorry for not providing many details. I fell asleep during debugging 😂.) After reading your code I suspect that the following function you provided is actually not working as you might expect:

```lua
vim.api.nvim_create_augroup('SmoothCursor', { clear = true })

vim.api.nvim_create_autocmd({ 'BufEnter' }, {
  group = 'SmoothCursor',
  callback = function()
    callback.switch_buf()
    callback.detect_filetype() -- This line here.
    callback.set_buffer_to_prev_pos()
    callback.sc_callback()
  end,
})
```

Because if you try to print out `vim.bo.bt` in a `BufEnter`-autocmd, you will not get `'terminal'` as the return value, because it has not been set. I was trying to find an alternative, which the `vim.bo.bt` has been set but it seems that there is no such autocmd...

**Comment by gen740** [comment]
I know that issue and I fixed it in dev branch.

**Comment by gen740** [comment]
But in dev branch fly-in effect is a bit broken...

**Comment by nyngwang** [comment]
> I know that issue and I fixed it in dev branch.

Good news to me and thank you :) Since I don't know how to use Vim/NeoVim's async functions, so it turns out to be a good sleep since I can't solve it myself, lol. (and I was thinking about whether I should post a question on stackexchange.com to ask about how to detect filetype/buftype in autocmd)
