### ISSUE TITLE
Cannot change the cursor with another nerd-font glyph

### ISSUE THREAD

**Issue by nyngwang** [gen740/SmoothCursor.nvim#37]
I'm using the following config: 

```lua
require('smoothcursor').setup {
  autostart = true,
  fancy = {
    enable = true,
  },
  threshold = 1,
  flyin_effect = 'top',
  disable_float_win = true,
}
```

It seems that adding additional lines `cursor = '>'` and `fancy.head.cursor = '>'` into the `setup` table won't change anything... (In my case, only the color of the default-shape cursor got changed.)

Thank you for reading this. (just resolved many of my config problems and need to change some visual stuff for fun now)

**Comment by gen740** [comment]
It's weird... I confirmed that the settings on the master branch are working properly. However, it's possible that the configuration has been overridden somewhere else.
