### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by Joarell** [gen740/SmoothCursor.nvim#42]
Hi!
I hope you are doing great!
I just would like to know how would be the new setup to the plugin after your huge upgrade?
The README config is no longer working.
Have a nice day!
![image](https://github.com/gen740/SmoothCursor.nvim/assets/42722369/894a9481-5e72-43c2-bb2b-3ea495a6f111)
![image](https://github.com/gen740/SmoothCursor.nvim/assets/42722369/ca50fa94-3a52-46ea-ac72-c90687ba1d77)

**Comment by gen740** [comment]
Thank you for your issue! I've tried to reproduce the issue on my end but couldn't get the same result. Could you please share your configuration settings to help me better understand the problem?

It seems like there's an error due to the version of Neovim. Could you please tell me the version?

**Comment by Xiione** [comment]
Was viewing this issue just as the fix was pushed, lol. Thank you for your work!

**Comment by gen740** [comment]
I believe this change should resolve the issue. Feel free to reopen it if you encounter any problems!

**Comment by Joarell** [comment]
Thank you to solve the issue!
And sorry to not answer you before. My bad.
I was wondering if the Matrix option is already available. 😎

**Comment by gen740** [comment]
TBH, the matrix option is available by setting `type = "matrix"` (but not yet completed).
I'll create a new PR later!

**Comment by gen740** [comment]
**demo**

https://github.com/gen740/SmoothCursor.nvim/assets/54583542/78edf4b2-824f-4d9a-ac8d-4d57695e0407
