### ISSUE TITLE
not working with neo-tree?

### ISSUE THREAD

**Issue by a1401358759** [gen740/SmoothCursor.nvim#50]
I added this plugin with lazy.nvim, but it didn't get any effect in neo-tree.
Please, take a look at my settings.

```lua
{
    "gen740/SmoothCursor.nvim",
    lazy = false,
    config = function()
      require("smoothcursor").setup({})
    end,
}
```

**Comment by gen740** [comment]
I assume this issue occurred because the `signcolumn` was set to `no` in Neo-tree. Could you check the `signcolumn` value when Neo-tree is opened?(`:set signcolumn?`)

**Comment by a1401358759** [comment]
@gen740 yes, it is indeed set to no
