### ISSUE TITLE
How to disable it on popup window? like lsp hover?

### ISSUE THREAD

**Issue by semi710** [gen740/SmoothCursor.nvim#51]

**Comment by gen740** [comment]
There is an option called `disable_float_win`.
https://github.com/gen740/SmoothCursor.nvim/blob/cc8780622a7b7c328f774762fa2d97d9f83be828/doc/smoothcursor.txt#L83
Setting this to `true` should meet your need!

example:
```lua
require('smoothcursor').setup {
  disable_float_win = true
 }
```

**Comment by semi710** [comment]
Thanks mate
