### ISSUE TITLE
List of valid cursor shapes 

### ISSUE THREAD

**Issue by mansmohaali** [gen740/SmoothCursor.nvim#60]
Hello, first of all great thanks to all the effort, I discovered the amazing GitHub due "Josh Medeski" YouTube's channels @joshmedeski.

I was trying to customize my cursor header, but i am sure if they are supported, for example:

1. I also try the "nf-fa-arrow_circle_right", it's icon symbol is  and it's utf-16 code is "\uf0a9"; however this is the error i am getting:
   -  Failed to run `config` for SmoothCursor.nvim

Vim:E239: Invalid sign text:  

# stacktrace:
  - /SmoothCursor.nvim/lua/smoothcursor/init.lua:124 _in_ **smoothcursor_define_signs**
  - /SmoothCursor.nvim/lua/smoothcursor/init.lua:133 _in_ **init_and_start**
  - /SmoothCursor.nvim/lua/smoothcursor/init.lua:175 _in_ **setup**
  - ~/.config/nvim/lua/mansoor/plugins/smooth-cursor.lua:4 _in_ **config**
  - ~/.config/nvim/lua/mansoor/lazy.lua:14
  - init.lua:5
Press ENTER or type command to continue

I am getting the same error try to use any nerd font icon on the nerd-font website: https://www.nerdfonts.com/cheat-sheet

Thanks in advance.

**Comment by joshmedeski** [comment]
Can you share your config code? You'll need to make sure the character is wrapper in quotes.

**Comment by mansmohaali** [comment]
![image](https://github.com/gen740/SmoothCursor.nvim/assets/94426775/2f741bc9-94de-4e70-bcf0-0bfb6fa7a237)
This is the error i am getting when i chage the cursor to my favorite cursor icon.

**Comment by joshmedeski** [comment]
That's odd, perhaps try the UTF code? Otherwise we'll have to lean on @gen740's knowledge on the plugin to debug further.

**Comment by gen740** [comment]
According to `:h E239`
> Define the text that is displayed when there is no icon or the GUI is not being used.  Only printable characters are allowed and they must occupy one or two display cells.

This implies that a sign must consist of one or two characters. In @mansmohaali's configuration, the cursor appears to contain three characters (one icon and two spaces), which is invalid.

**Comment by gen740** [comment]
This issue has been closed due to inactivity.
 If you have any further questions or concerns, please feel free to reopen it!
