### ISSUE TITLE
[Bug?] SmoothCursor is showing when moving between splits of the same buffer

### ISSUE THREAD

**Issue by ofirgall** [gen740/SmoothCursor.nvim#8]

**Comment by gen740** [comment]
Thank you for your suggestion!!

Since this plugin use 'sign' to show sub-cursor. This cannot be avoided.

**Comment by gen740** [comment]
It seems to be rare to open the same page of the same buffer in a single window.

**Comment by ofirgall** [comment]
For you its rare, I'm mostly work with the same buffer in a vertical split. this is deal breaker for me, sorry :(
